# Generated by Django 5.1.1 on 2024-11-30 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_address2_alter_student_address_student2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address2',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmodule.address'),
        ),
        migrations.AlterField(
            model_name='student2',
            name='addresses',
            field=models.ManyToManyField(to='bookmodule.address'),
        ),
    ]
